src/assets/img/dataset-body.svg
src/assets/img/dataset-header.svg
src/assets/img/resource-00a272.svg
src/assets/img/resource-header.svg
src/assets/img/xmark-solid.svg
src/pages/aboutPage/index.js
src/pages/datasetDetailPage/DatasetDetail.js
src/pages/glossaryPage/index.js
src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js
src/pages/participatingResourcesPage/SearchResult/SearchResult.js
src/pages/searchCatalogPage/SearchBox/index.js

One time migration: merge code from develop to development branch 1.2.0

Merge from develop to dev-1.2.0

---

src/components/common/ScrollButton.js
src/pages/App.js

Back to top UI implementation

---

src/pages/siteUpdatePage/SiteUpdateResult/SiteUpdateResult.js
src/pages/siteUpdatePage/SiteUpdateResult/index.js
src/redux/actions/actionTypes.js
src/redux/actions/applicationActions.js
src/redux/reducers/applicationReducer.js

Partial Load of Update date

---

src/pages/datasetDetailPage/DatasetDetail.js

task PODCAT-781
Remove "Case ID" from data values under Project attribute.

PODCAT-773 Remove "Case ID" from data values under Project attribute

---

src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js

Added "https://" if http or https not found at the beginning.

PODCAT-740 Multiple links in Resource Data Access field

---

src/assets/img/Scroll_to_top.svg
src/assets/img/Scroll_to_top_active.svg
src/components/common/ScrollButton.js

Changed the button to the svg and created another svg when active. changed the "left: 95%" to use "right: 25px"

Podcat 683 back to top button 

---

src/assets/img/Scroll_to_top.svg
src/assets/img/Scroll_to_top_active.svg
src/components/common/ScrollButton.js

* PODCAT-683
Changed the button to the svg and created another svg when active. changed the "left: 95%" to use "right: 25px"
* uploaded Scroll_to_top.svg
uploaded Scroll_to_top.svg

Podcat 683 back to top button  (#187)

---

src/pages/datasetDetailPage/DatasetDetail.js

Used map instead of listing items one by one.

PODCAT-800 Missing link in the Published in section

---

src/pages/datasetDetailPage/DatasetDetail.js

Changed the confusing logic for map to make it more clear.

Podcat 794 Mismatch between Grant ID and Grant Name

---

src/pages/landingPage/SiteUpdateWidget/SiteUpdateWidget.js

Fixed the bug that one word doesn't show in one line.

PODCAT-790

---

src/pages/landingPage/SiteUpdateWidget/SiteUpdateWidget.js

Fixed the bug that one word doesn't show in one line.

PODCAT-790 (#195)

---

src/pages/datasetDetailPage/DatasetDetail.js

Handled multiple Grant ID and handled when Grant ID doesn't have a name.

Podcat 822 - Dataset Detail Page does not open

---

src/pages/landingPage/landingPage.css

changed the line-height from 39px to 46px

PODCAT-820 Letters are so close to each other

---

src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js

Corrected the Resource Type on Resource Details Page

PODCAT-772: Resource Details Page - Resource Type not correct.

---

src/components/Accordion/Accordion.js
src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js
src/pages/participatingResourceDetailPage/participatingResourceDetailPage.css

* Update PODCAT-744 feature: fix participating resource detail page collapse issue
* Update PODCAT-744 feature: fix participating resource page filter accordion issue

Update Podcat-744 feature: fix collapse and expand UI issue (#207)

---

src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js

Changed some css;
Used map to handle multiple urls.

PODCAT-847: Overlay Primary Dataset Scope bubble on text

---

src/pages/glossaryPage/index.js

task PODCAT-852: Update Glossary Term Category in Front End

PODCAT-813: Update Glossary Term Category - Image Type

---

src/pages/aboutPage/index.js
src/pages/landingPage/index.js

task PODCAT-844: Update existing site-wide language for adding Analytic Tool front end part

PODCAT-825: New Resource Type - Tools, Technical

---

package.json
public/index.html
src/components/common/DonutChart.js
src/components/common/Histogram.js
src/pages/aboutPage/aboutPage.css
src/pages/datasetDetailPage/DatasetDetail.js

Used react-bootstrap to create a dropdown menu;
Used recharts to implement pie chart and histogram.

PODCAT-718: Data Details Page: Graphics - Implementation

---

src/components/common/Histogram.js

1. Used the following labels: "0 to 4," "5 to 9,"... "<40" (so ommitting the word "years" and 'Pediatric and Young Adult').
2. Added a label to the x axis that reads "Age (years)" y axis "Cases"
3. Changed the tooltip from "value" to "Cases"

PODCAT-857: Dataset Detail page: Case age Diagnosis chart

---

src/pages/glossaryPage/index.js

Added Analytic Tool, PROSPR, GEO and ScPCA abbreviation in Glossary page

PODCAT-859: Glossary page - new resources abbreviation

---

src/components/common/DonutChart.js

Changed the longest length of payload.name

PODCAT-863: Overlapping of text in Donut chart

---

src/components/common/Histogram.js

Vertical axis label 'cases' shifted up

PODCAT-862: Vertical axis label 'cases' shifted up

---

package-lock.json
src/pages/datasetDetailPage/datasetDetailPage.css

task PODCAT-867:
Update the breadcrumbs across the site so that the individual components are more distinct.
Update the carrots between items to be #3d4551
Update the page items to have underlines to more clearly denote they are links.

PODCAT-853: A More Distinguished Bread Crumb

---

src/pages/datasetDetailPage/DatasetDetail.js

handled more than one links in the Data Details Description

PODCAT-858: Data Details Page: Links in the Description

---

src/pages/glossaryPage/index.js

Added abbreviation for CLIC, VPCC, CGC on Glossary page

PODCAT-876: Glossary page - new resources abbreviation (CLIC, VPCC, CGC)

---

src/pages/siteUpdatePage/SiteUpdateResult/SiteUpdateResult.js

Adjusted size for clinical icon and added 1 px more space on the bottom.

PODCAT-708: Adjusted size for clinical icon

---

src/pages/participatingResourcesPage/Filters/Filters.js

- Added a border element at the top of the filter column
- Changes the filter section title to 'Resource Filter' and increased weight of the title
- Increased weight of the response options
- Added a clear button next to the new 'Research Filter' title and match the style and placement of the Search Catalog page

PODCAT-866: Participating Resources - Update Filter Styling and Function

---

src/pages/glossaryPage/index.js

Changed term category to display Resource Type

PODCAT-879: Glossary page - wrong term category for the Analytic Tool

---

src/components/Accordion/Accordion.css

weight of the response options became bold

PODCAT-883: Increased weight of the response options

---

src/pages/searchCatalogPage/SearchResult/SearchResult.js

PODCAT-886: Make GEO Study Identifier linkable on Search Catalog page
PODCAT-887: Make dbGaP Study Identifier linkable on Search Catalog page
PODCAT-888: On the Catalog Search page, update the Card View cards to allow for active links when a piece of linked information is displayed.

PODCAT-884: Search Catalog - Implement usable links parity in Card view.

---

src/pages/searchCatalogPage/SearchResult/SearchResult.js

PODCAT-884

---

src/pages/searchCatalogPage/SearchResult/SearchResult.js

PODCAT-884 (#242)

---

src/pages/datasetDetailPage/DatasetDetail.js

PODCAT-924: Issue in the CASE PROBAND field

---

src/pages/glossaryPage/index.js

Added Epidemiologic and Proband to glossary

PODCAT-926: Update front end to include new glossaries

---

src/pages/datasetDetailPage/DatasetDetail.js

Showed multiple GEO STUDY IDENTIFIER

PODCAT-922: The issue in the GEO STUDY IDENTIFIER field

---

src/pages/datasetDetailPage/DatasetDetail.js

Deleted the useless console log

Deleted the useless console log

---

src/pages/participatingResourcesPage/SearchResult/SearchResult.js

PODCAT-975: The end of the title is below the underline

---

src/components/common/NavBar.js

Add a Link to the CCDI Resource on the Menu bar

PODCAT-949: Add a Link to the CCDI Resource on the Menu bar

---

src/components/Pagination/index.js
src/pages/datasetDetailPage/DatasetDetail.js
src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js
src/pages/participatingResourcesPage/SearchResult/SearchResult.js

PODCAT-929: CCDC Web Elements ID request

---

src/components/Pagination/index.js
src/pages/datasetDetailPage/DatasetDetail.js
src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js
src/pages/participatingResourcesPage/SearchResult/SearchResult.js

* Added search_catalog_total_count, dataset_summaries_detail_count, dataset_summaries_count
Added search_catalog_total_count, dataset_summaries_detail_count, dataset_summaries_count
* Added id to Core Data Elements
Added id to Core Data Elements
* Added id for some additional elements
Added id for some additional elements
* Added id toLocaleLowerCase logic
Added id toLocaleLowerCase logic
* change name to participating_resource
change name to participating_resource

PODCAT-929: CCDC Web Elements ID request (#260)

---

src/components/Pagination/index.js

changed the id to total_records_count

changed the id to total_records_count

---

src/pages/datasetDetailPage/DatasetDetail.js

Fixed data repository issue (#267)

---

src/pages/participatingResourcesPage/SearchResult/SearchResult.js

Email appear to each contact separately, as on the Resource Detail page

PODCAT-1015: Participating Resources page: email link doesn't appear correct.

---

src/pages/datasetDetailPage/DatasetDetail.js

Made the SRA study id to be a link

PODCAT-1022: SRA study should be a link

---

src/pages/datasetDetailPage/DatasetDetail.js

* PODCAT-1022: SRA study should be a link
Added SRA STUDY IDENTIFIER link out
* changed title
changed title

PODCAT-1022: SRA study should be a link (#280)

---

src/pages/landingPage/index.js

Clicking should navigate to: https://datacatalog.ccdi.cancer.gov/search

PODCAT-1054: Home page 'Explore the Catalog' link Update

---

src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js

task PODCAT-1061: Show 2 separate links on Xena browser Data Access part

PODCAT-1055: Show 2 separate links on Xena browser Data Access part

---

src/pages/datasetDetailPage/DatasetDetail.js

task [PODCAT-1062]: Order the identifiers
task [PODCAT-1063]: Make Clinical trial identifier linkable

PODCAT-1020: Additional Data Element - Identifier order

---

src/pages/datasetDetailPage/DatasetDetail.js

* Changed sort function
Changed sort function
* Added Clinical Trial Identifier
Added clinical trail id
* Added linkout for clinical_trail_identifier
Added linkout for clinical_trail_identifier

PODCAT-1020: Additional Data Element - Identifier order (#286)

---

src/pages/datasetDetailPage/DatasetDetail.js

task [PODCAT-1010]: Implement resource export script

PODCAT-1002: QA Report (take 2) add id in specific format

---

src/pages/datasetDetailPage/DatasetDetail.js

* Added poc_email
Added poc_email
* Added Dataset description
Added Dataset description
* Added published_in
Added published_in
* Added sra_study_identifier, geo_study_identifier, clinical_trail_identifier
Added sra_study_identifier, geo_study_identifier, clinical_trail_identifier
* Added dbgap_study_identifier
Added dbgap_study_identifier

PODCAT-1002: QA Report (take 2) add id in specific format (#290)

---

src/pages/datasetDetailPage/DatasetDetail.js
src/pages/datasetDetailPage/datasetDetailPage.css

* Update UI to resolve automation issue
* Update UI
* Update UI to solve automation issue

Fix UI hidden issue (#292)

---

src/pages/datasetDetailPage/DatasetDetail.js
src/pages/datasetDetailPage/datasetDetailPage.css

* Update UI to resolve automation issue
* Update UI
* Update UI to solve automation issue
* Update UI to fix automation problem
* Adjust UI for poc, dataset description , dbgap and published in fields

Adjust UI to support automation (#294)

---

src/pages/siteUpdatePage/SiteUpdateResult/SiteUpdateResult.js

Clinical icon described as Clinical icon
Epidemiologic icon described as Epidemiologic icon Genomics/Omics icon describe as Genomics/Omic icon Imaging icon describe as Imaging icon
Xenograft icon describe as Xenograft icon

PODCAT-1092: Update Updates Icon Alt-Text

---

src/components/Accordion/AccordionItem.js
src/components/common/NavBar.js
src/pages/landingPage/index.js
src/pages/searchCatalogPage/Filters/FilterItem.js

The Document Search field includes a label.
Catalog search on the Home page includes a label.
The Resource checks on the Search Catalog include a label. The Resource Type and Data Content Types on the Participating Resource page includes a label.

PODCAT-1091: Input Fields Missing Form Label

---

src/components/Accordion/AccordionItem.js
src/pages/searchCatalogPage/Filters/FilterItem.js

changed the way of putting <label>

PODCAT-1103: Filter does not work properly

---

src/components/Accordion/AccordionItem.js
src/pages/searchCatalogPage/Filters/FilterItem.js

* removed <label>
removed <label>
* Added label on Participating Resources page
Added label on Participating Resources page
* Added label on Search Catalog page
Added label on Search Catalog page

PODCAT-1103: Filter does not work properly (#306)

---

src/components/Accordion/AccordionItem.js
src/pages/participatingResourcesPage/SearchResult/SearchResult.js
src/pages/searchCatalogPage/Filters/FilterItem.js

PODCAT-1104: POC contact link does not work correct

---

src/pages/participatingResourcesPage/SearchResult/SearchResult.js

* removed <label>
removed <label>
* Added label on Participating Resources page
Added label on Participating Resources page
* Added label on Search Catalog page
Added label on Search Catalog page
* PODCAT-1104: POC contact link does not work correct
added trim() to array item

PODCAT-1104: POC contact link does not work correct (#312)

---

src/components/common/NavBar.js
src/pages/landingPage/index.js

PODCAT-1131: Add Mobile Nav Button description.

---

src/components/common/NavBar.js
src/pages/landingPage/index.js

PODCAT-1131: Add Mobile Nav Button description. (#319)

---

src/pages/participatingResourcesPage/Filters/Filters.js

made the icon smaller so that it doesn't go to another line

PODCAT-1136: Participating Resources: clear button does not work correctly when zoom out

---

src/pages/participatingResourcesPage/Filters/Filters.js

Changed position to be absolute;

PODCAT-1136: Participating Resources: clear button reload circle not correct zoom out

---

src/components/common/Header.js

added media query when it is < 1200px the position becomes absolute

PODCAT-1152: Link-back bar responsive

---

src/components/common/Header.js

added media query when it is < 1200px the position becomes absolute

PODCAT-1152: Link-back bar responsive (#327)

---

src/pages/datasetDetailPage/DatasetDetail.js

changed table cell background to transparent

PODCAT-1214: Grant Information Table Background Color

---

public/robots.txt
src/components/common/Header.js
src/components/common/NavBar.css
src/components/common/NavBar.js

ccdc government shutdown banner

ccdc government shutdown banner

---

src/components/common/NavBar.css

hanged padding top for body to 310px

Banner: changed padding top for body

---

src/components/common/NavBar.css

hanged padding top for body to 310px

Banner: changed padding top for body (#352)

---

src/pages/App.js
src/pages/glossaryPage/glossaryPageController.js
src/pages/glossaryPage/glossaryPageView.js
src/redux/actions/applicationActions.js
src/redux/reducers/applicationReducer.js
src/redux/reducers/initialState.js

Display glossary page with data from API

PODCAT-1294: Display glossary page with data from API

---

src/pages/App.js
src/pages/glossaryPage/glossaryPageController.js
src/pages/glossaryPage/glossaryPageView.js
src/redux/actions/applicationActions.js
src/redux/reducers/applicationReducer.js
src/redux/reducers/initialState.js

* Added nav to glossary page
added nav
* change app.js
* Added loadGlossaryTermsByFirstLetter logic
Added loadGlossaryTermsByFirstLetter logic
* Added external link on glossary page

PODCAT-1294: Display glossary page with data from API (#368)

---

src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js

Added link function to resource page

PODCAT-1312: Not function link in the 'About this resource' section

---

src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js

Fixed link color on Resource detail page

PODCAT-1312: Fixed link color on Resource detail page

---

src/components/common/DonutChart.js

Added comma to the donut chart on Dataset Page

PODCAT-1331: Dataset Page Donut Chart Comma

---

src/pages/participatingResourcesPage/SearchResult/SearchResult.js

PODCAT-1340: 2 URLs are open as one and that gave the error

---

src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js

Updated the Resource detail description using ReactHtmlParser

PODCAT-1345: Resource Description Linked Text.

---

src/pages/participatingResourceDetailPage/ParticipatingResourceDetail.js

Updated the Resource detail description using ReactHtmlParser

Updated Resource detail description (#386)

---

src/assets/img/PauseButtonIcon.svg
src/assets/img/StartButtonIcon.svg
src/pages/landingPage/SiteUpdateWidget/SiteUpdateWidget.js

Add a pause/play button to the 'Featured Item' carousel

PODCAT-1085: Implement - 'Featured Item' Carousel Pause

---

src/pages/participatingResourcesPage/SearchResult/SearchResult.js

the links that are in the descriptions should be functional link on the Participating resource page, at least it should be text, not HTML code

PODCAT-1362: Participating resource page-> links in description

---

src/assets/img/dataset-body-grey.svg
src/assets/img/dataset-body-white.svg
src/components/common/NavBar.js

Update the 'CCDI Studies' menu bar to include additional links to other CCDI content.

PODCAT-1372: Additional Menu Bar Links

---

src/assets/img/dataset-body-grey.svg
src/assets/img/dataset-body-white.svg
src/components/common/NavBar.js

PODCAT-1372: remove link icon from navbar
